# Este modelo do AWS SAM foi gerado a partir da configuração da sua função. Se sua
# função tiver um ou mais acionadores, observe que os recursos da AWS associados a
# esses acionadores não estão totalmente especificados nesse modelo e incluem
# valores de espaço reservado. Abra esse modelo no AWS Application Composer ou em
# seu IDE favorito e modifique-o para especificar uma aplicação com tecnologia sem
# servidor com outros recursos da AWS.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  multipedidoscruditem:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:Scan
                - dynamodb:UpdateItem
              Resource: arn:aws:dynamodb:us-east-1:248278816999:table/*
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:us-east-1:248278816999:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:us-east-1:248278816999:log-group:/aws/lambda/multipedidos-crud-item:*
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /items
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: ANY
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
